--1. DDL
--1-1. 다른 테이블 참조하여 테이블 생성
CREATE TABLE COURSE_PROFESSOR1(CNO, CNAME, PNO, PNAME, AVGRES)
    AS SELECT CNO
            , C.CNAME
            , PNO
            , P.PNAME
            , ROUND(AVG(RESULT), 2)
          FROM COURSE C
          NATURAL JOIN SCORE SC
          NATURAL JOIN PROFESSOR P
          GROUP BY CNO, C.CNAME, PNO, P.PNAME;
          
SELECT *
    FROM COURSE_PROFESSOR1;

--STUDENT의 SNO, SNAME, MAJOR, SYEAR SCORE의 RESULT, SCGRADE의 GRADE 가지는 테이블 생성
--SCORE_GRADE
CREATE TABLE SCORE_GRADE1(SNO, SNAME, MAJOR, SYEAR, RESULT, GRADE)
    AS SELECT SNO
             , ST.SNAME
             , ST.MAJOR
             , ST.SYEAR
             , SC.RESULT
             , SG.GRADE
            FROM STUDENT ST
            NATURAL JOIN SCORE SC
            JOIN SCGRADE SG
            ON SC.RESULT BETWEEN SG.LOSCORE AND SG.HISCORE;
            
SELECT *
    FROM SCORE_GRADE1
    ORDER BY SNO, RESULT DESC;
    
--1-2. ALTER
--컬럼을 추가하는 ADD
--EMP_COPY 테이블에 ADDR컬럼 추가
ALTER TABLE EMP_COPY1
    ADD ADDR VARCHAR2(50);

--컬럼명을 변경하는 RENAME
--EMP_COPY 테이블의 SAL 컬럼을 SALARY 변경
ALTER TABLE EMP_COPY1
    RENAME COLUMN SAL TO SALARY;

--컬럼의 데이터타입을 변경하는 MODIFY
--EMP_COPY 테이블의 ENO컬럼의 데이터타입을 VARCHAR2(4) -> VARCHAR2(10)
ALTER TABLE EMP_COPY1
    MODIFY ENO VARCHAR2(10);

--컬럼을 삭제하는 DROP
--EMP_COPY 테이블에 ADDR컬럼 삭제
ALTER TABLE EMP_COPY1
    DROP COLUMN ADDR;
    
DESC EMP_COPY1;

SELECT *
    FROM EMP_COPY1;
    
--1-3. 테이블을 삭제하는 DROP
CREATE TABLE SCORE_COPY1
    AS SELECT * FROM SCORE;

SELECT * FROM SCORE_COPY1;

--SCORE_COPY 테이블 삭제
DROP TABLE SCORE_COPY1;

--TIMESTAMP로 DELETE된 데이터 조회
--ENTERPRISE 버전에서는 FLASHBACK이라는 기능으로 DROP한 테이블 복구 가능
DELETE FROM EMP_COPY1;

SELECT *
    FROM EMP_COPY1;

--TIMESTAMP 이용해서 삭제된 데이터 복구
INSERT INTO EMP_COPY1
SELECT * 
    FROM EMP_COPY1
    AS OF TIMESTAMP(SYSTIMESTAMP -  INTERVAL '10' MINUTE);

--1-4. 테이블의 이름을 변경하는 RENAME
RENAME EMP_COPY1 TO EMP_TEMP1;

--1-5. 테이블의 데이터를 모두 삭제하는 TRUNCATE
TRUNCATE TABLE EMP_TEMP1;

SELECT *
    FROM EMP_TEMP1;